/* --- 1. 羁绊数据 (保持不变) --- */
const synergyData = [
    { id: "舞阳城", name: "【舞阳城】", requiredCount: 3, desc: "羁绊内的棋子攻击时会召唤黑衣死士,向敌人发起自爆冲锋。", pieces: ["雷音尊使", "黑天尊使", "红衣尊使", "薛魔主"] },
    { id: "首席弟子", name: "【首席弟子】", requiredCount: 3, desc: "羁绊内的棋子每次使用技能,都会给周围1格的所有棋子提高4.8%攻击力,最多叠加10层。", pieces: ["首席碎梦", "首席铁衣", "首席血河", "首席潮光", "首席鸿音", "首席玄机", "首席云瑶"] },
    { id: "初级弟子", name: "【初级弟子】", requiredCount: 3, desc: "羁绊内的棋子每次使用技能,都会给周围1格的所有棋子提高3%攻击力,最多叠加10层。", pieces: ["初级龙吟", "初级九灵", "初级神相", "初级素问", "初级荒羽", "初级沧澜"] },
    { id: "白石神殿", name: "【白石神殿】", requiredCount: 3, desc: "白石神殿所属棋子数量越多,羁绊内所有棋子造成伤害越高。提高棋子数量*10%的伤害。", pieces: ["独孤威", "孙不恭", "乌勒奴", "萨迦石神"] },
    { id: "逆水之寒", name: "【逆水之寒】", requiredCount: 3, desc: "每次攻击造成伤害时,会对目标周围小范围内的敌人造成一半的伤害,冷却1秒。", pieces: ["雷商羽", "高衙内", "戚少商", "刘独峰", "顾惜朝"] },
    { id: "四大名捕", name: "【四大名捕】", requiredCount: 4, desc: "所有自己的棋子每次击败敌人,可以额外获得2金币。", pieces: ["冷血", "铁手", "无情", "追命"] },
    { id: "武林风云", name: "【武林风云】", requiredCount: 3, desc: "每隔5秒会标记一名敌人,任何击败该敌人的棋子会在10秒内伤害提高100%。", pieces: ["陈斩槐", "醉仙", "刀狂", "楚相玉"] },
    { id: "血怖宫", name: "【血怖宫】", requiredCount: 4, desc: "持有的棋子种类越多,所有血怖宫尊使的伤害越高。每种棋子增加5%的伤害。", pieces: ["血鸦尊使", "血蛇尊使", "魔尊血鹤", "阿冷"] },
    { id: "天義十巫", name: "【天義十巫】", requiredCount: 5, desc: "召唤金乌降临,金乌攻击造成内功与外功伤害。金乌的伤害随战旗等级提高。", pieces: ["木巫青黎", "水巫沧洄", "金巫锋罡", "土巫嶂煞", "火巫烬炎"] },
    { id: "一梦黄粱", name: "【一梦黄粱】", requiredCount: 3, desc: "羁绊内的棋子激活特殊效果,详情见各棋子的技能描述。", pieces: ["唐春雨", "陈之望", "李白", "江无射", "柳星闻"] },
    { id: "四时流转", name: "【四时流转】", requiredCount: 3, desc: "每隔10秒,羁绊内棋子获得一种四季效果。【春】:伤害提高50%;【夏】:攻击力提高50%;【秋】:所有友方伤害提高30%,【冬】:冷却缩短30%。", pieces: ["初级素问", "雷商羽", "李白", "魔尊血鹤", "楚相玉"] },
    { id: "财迷心窍", name: "【财迷心窍】", requiredCount: 3, desc: "战旗产出的金币数量提高20%。", pieces: ["孙不恭", "陈之望", "高衙内"] },
    { id: "人剑合一", name: "【人剑合一】", requiredCount: 3, desc: "羁绊内棋子每次施放技能,都会使下一次技能伤害提高10%,最多叠加5层。", pieces: ["冷血", "首席碎梦", "刀狂", "血鸦尊使", "柳星闻"] },
    { id: "幻变随心", name: "【幻变随心】", requiredCount: 3, desc: "所有友方棋子的冷却时间缩短30%。", pieces: ["初级九灵", "首席潮光", "水巫沧洄", "首席云瑶", "阿冷"] },
    { id: "千钧一击", name: "【千钧一击】", requiredCount: 3, desc: "羁绊内棋子外功攻击提高50%。", pieces: ["黑天尊使", "初级沧澜", "首席玄机", "萨迦石神"] },
    { id: "万毒噬天", name: "【万毒噬天】", requiredCount: 3, desc: "羁绊内棋子内功攻击提高50%。", pieces: ["唐春雨", "乌勒奴", "木巫青黎", "血蛇尊使", "薛魔主"] },
    { id: "断石分金", name: "【断石分金】", requiredCount: 3, desc: "羁绊内棋子攻击时,使敌人的外功防御力降低40%。", pieces: ["初级荒羽", "陈斩槐", "无情", "金巫锋罡", "顾惜朝"] },
    { id: "烈焰熔金", name: "【烈焰熔金】", requiredCount: 3, desc: "羁绊内棋子攻击时,使敌人的内功防御力降低40%。", pieces: ["初级神相", "铁手", "首席血河", "火巫烬炎"] },
    { id: "轻歌曼舞", name: "【轻歌曼舞】", requiredCount: 3, desc: "所有友方棋子造成的伤害提高20%。", pieces: ["醉仙", "追命", "首席鸿音", "红衣尊使"] },
    { id: "一夫当关", name: "【一夫当关】", requiredCount: 3, desc: "羁绊内棋子对生命值高于70%的敌人,造成的伤害提高80%。", pieces: ["首席铁衣", "土巫嶂煞", "江无射", "刘独峰"] },
    { id: "雷霆之力", name: "【雷霆之力】", requiredCount: 3, desc: "羁绊内棋子攻击时,落下雷电造成伤害,并降低防御力20%。", pieces: ["雷音尊使", "独孤威", "初级龙吟", "戚少商"] },
];

/* --- 2. 棋子总数据 (已合并胶囊数据) --- */
const pieceMasterData = {
    // --- 蓝卡 ---
    "雷音尊使": { quality: "蓝", img: "image/雷音尊使.png", jineng: "【共奏蒹葭】:静心弹奏，对周围敌人造成伤害，提高友方内外功伤害20%/30%/40%", attackType: "内功", rangeType: "范围", utilityType: "增益" },
    "黑天尊使": { quality: "蓝", img: "image/黑天尊使.png", jineng: "【饮血飞爪】:连续攻击，对单体敌人造成巨额伤害，对护盾三倍伤害", attackType: "外功", rangeType: "单体", utilityType: "破盾" },
    "初级龙吟": { quality: "蓝", img: "image/初级龙吟.png", jineng: "【吟风】:连续挥出剑气，造成多段范围伤害，对护盾三倍伤害", attackType: "内功", rangeType: "范围", utilityType: "破盾" },
    "初级九灵": { quality: "蓝", img: "image/初级九灵.png", jineng: "【破梦】:对敌人造成范围伤害井驱散恢复效果\n【灵犀三现】:对范围内的敌人造成三段伤害，并驱散恢复效果", attackType: "内功", rangeType: "范围", utilityType: "驱散" },
    "初级神相": { quality: "蓝", img: "image/初级神相.png", jineng: "【御风】:对直线上的敌人造成内功伤害。\n【凤凰展翅】:对范围内的敌人造成内功伤害。", attackType: "内功", rangeType: "范围", utilityType: "" },
    "初级素问": { quality: "蓝", img: "image/初级素问.png", jineng: "【初绽】:短时间内提升单个友方所有伤害40%/60%/80%", attackType: "无攻击", rangeType: "单体", utilityType: "增益" },
    "初级荒羽": { quality: "蓝", img: "image/初级荒羽.png", jineng: "【猎风刃】:连续施放三段猎风刃，造成范围伤害，并驱散恢复效果", attackType: "外功", rangeType: "范围", utilityType: "驱散" },
    "初级沧澜": { quality: "蓝", img: "image/初级沧澜.png", jineng: "【狂涛衔锋】:对面前扇形范围造成大量伤害。", attackType: "外功", rangeType: "范围", utilityType: "" },
    "独孤威": { quality: "蓝", img: "image/独孤威.png", jineng: "【雷霆急枪】:连续刺击，对单个敌人造成大量伤害", attackType: "外功", rangeType: "单体", utilityType: "" },
    "孙不恭": { quality: "蓝", img: "image/孙不恭.png", jineng: "【挖掘宝藏】:每隔10秒挖掘一次宝藏，获得金币1/2/3枚，自己每额外存在一个孙不恭，挖掘的金币多增加1枚，最多额外增加2枚/3枚/5枚。", attackType: "无攻击", rangeType: "", utilityType: "金币" },
    "冷血": { quality: "蓝", img: "image/冷血.png", jineng: "【碎影】:快速对单体目标造成大量伤害，并驱散恢复效果\n【刹那】:快速挥剑对前方范围内的敌人造成伤害，并驱散恢复效果", attackType: "外功", rangeType: "单体", utilityType: "驱散" },
    "铁手": { quality: "蓝", img: "image/铁手.png", jineng: "【焚天·绝】:对周围敌人造成大量伤害，对护盾三倍伤害", attackType: "内功", rangeType: "", utilityType: "破盾" },
    "无情": { quality: "蓝", img: "image/无情.png", jineng: "【暗器】:对单体敌人造成伤害对护盾三倍伤害\n【流星】:连续对单体敌人造成大量伤害，对护盾三倍伤害", attackType: "外功", rangeType: "单体", utilityType: "破盾" },
    "追命": { quality: "蓝", img: "image/追命.png", jineng: "【喷酒术】:喷射酒雾，对面前扇形区域敌人造成伤害，并使其受伤增加20%/30%/40%", attackType: "外功", rangeType: "", utilityType: "增益" },
    "陈斩槐": { quality: "蓝", img: "image/陈斩槐.png", jineng: "【霸道横栏】:对面前范围内的敌人造成巨大伤害，最后一段击倒敌人。", attackType: "外功", rangeType: "范围", utilityType: "控制" },
    "醉仙": { quality: "蓝", img: "image/醉仙.png", jineng: "【乾坤酒壶】:掷出酒壶，在地面形成潮湿地面，对敌人造成持续伤害井减速20%/30%/40%", attackType: "内功", rangeType: "范围", utilityType: "控制" },
    "唐春雨": { quality: "蓝", img: "image/唐春雨.png", jineng: "【万蛊蚀心】:连线两名敌人，持续造成伤害\n【羁绊】【一梦黄粱】:连线的敌人数量增加到6名。", attackType: "内功", rangeType: "范围", utilityType: "" },
    "陈之望": { quality: "蓝", img: "image/陈之望.png", jineng: "【千金之重】:召唤元宝砸下造成范围伤害，并获得2/3/5点金币。\n【羁绊】【一梦黄粱】:召唤财迷陷阱，持续造成伤害并减速。", attackType: "外功", rangeType: "范围", utilityType: "金币" },

    // --- 紫卡 ---
    "红衣尊使": { quality: "紫", img: "image/红衣尊使.png", jineng: "【惊鸿舞】:持续起舞，对周围敌人造成伤害井减速30%/35%/40%", attackType: "外功", rangeType: "范围", utilityType: "控制" },
    "首席碎梦": { quality: "紫", img: "image/首席碎梦.png", jineng: "【月影碎空】:挥出剑气，对直线上的敌人造成伤害，并驱散恢复效果\n【无尽·灭】:召唤三个黑影，一同施放技能", attackType: "外功", rangeType: "范围", utilityType: "驱散" },
    "首席铁衣": { quality: "紫", img: "image/首席铁衣.png", jineng: "【一以贯之】:对面前范围内的敌人造成大量伤害，对护盾三倍伤害", attackType: "外功", rangeType: "范围", utilityType: "破盾" },
    "首席血河": { quality: "紫", img: "image/首席血河.png", jineng: "【万夫莫敌】:对周围的敌人造成大量内功伤害，并驱散恢复效果", attackType: "内功", rangeType: "范围", utilityType: "驱散" },
    "首席潮光": { quality: "紫", img: "image/首席潮光.png", jineng: "【击水三千】:对直线上的敌人造成三段伤害\n【天泽露华】:展开领域，持续对大范围敌人造成伤害井减速30%/35%/40%。", attackType: "内功", rangeType: "范围", utilityType: "控制" },
    "首席鸿音": { quality: "紫", img: "image/首席鸿音.png", jineng: "【十面埋伏】:在目标区域降下法阵，持续造成伤害，对护盾三倍伤害", attackType: "内功", rangeType: "范围", utilityType: "破盾" },
    "首席玄机": { quality: "紫", img: "image/首席玄机.png", jineng: "【伏龙箭】:蓄力后发出强力一箭，造成大量伤害", attackType: "外功", rangeType: "范围", utilityType: "核心" },
    "首席云瑶": { quality: "紫", img: "image/首席云瑶.png", jineng: "【莲步惊蕊】:持续对直线上的敌人造成多段伤害", attackType: "内功", rangeType: "范围", utilityType: "核心" },
    "乌勒奴": { quality: "紫", img: "image/乌勒奴.png", jineng: "【诅咒·毒】:对敌人种下毒蛊诅咒，一段时间后引爆造成大量范围伤害和眩晕。", attackType: "内功", rangeType: "范围", utilityType: "控制" },
    "雷商羽": { quality: "紫", img: "image/雷商羽.png", jineng: "【惊雷笛】:吹奏雷笛，提高附近1格所有友方攻击速度50%/75%/100%", attackType: "无攻击", rangeType: "范围", utilityType: "增益" },
    "高衙内": { quality: "紫", img: "image/高衙内.png", jineng: "【赋税】:每隔10秒，获得当前持有金币数量0.3%/0.6%/1%的利息，最多10/20/30枚。", attackType: "无攻击", rangeType: "", utilityType: "金币" },
    "戚少商": { quality: "紫", img: "image/戚少商.png", jineng: "【神龙九现】:对范围内所有敌人造成伤害，并落下气剑，对护盾三倍伤害\n【惊鸿】:引爆气剑，造成范围伤害，对护盾三倍伤害", attackType: "内功", rangeType: "破盾", utilityType: "核心" },
    "刀狂": { quality: "紫", img: "image/刀狂.png", jineng: "【黯然斩】:向前方持续斩击对敌人造成大量伤害。", attackType: "外功", rangeType: "范围", utilityType: "" },
    "木巫青黎": { quality: "紫", img: "image/木巫青黎.png", jineng: "【苍魔荆生】:对面前敌人造成伤害井驱散恢复效果，附加【五行·木】。\n对带有【五行·水】的敌人附加【中毒】效果。", attackType: "内功", rangeType: "范围", utilityType: "驱散" },
    "土巫嶂煞": { quality: "紫", img: "image/土巫嶂煞.png", jineng: "【尘壑落墟】:生成冥墟对进入的敌人造成伤害和眩晕，并附加【五行·土】。\n对带有【五行·火】的敌人附加【减速】效果，使目标减速30%/40%/50%", attackType: "外功", rangeType: "范围", utilityType: "控制" },
    "火巫烬炎": { quality: "紫", img: "image/火巫烬炎.png", jineng: "【扶摇离火】:召唤火龙卷持续造成伤害，并附加【五行·火】\n对带有【五行·木】的敌人附加【炮火】效果，使目标内功受伤加重40%/50%/60%。", attackType: "内功", rangeType: "范围", utilityType: "增益" },
    "水巫沧洄": { quality: "紫", img: "image/水巫沧洄.png", jineng: "【叠浪虚危】:召唤水浪对直线敌人造成伤害，附加【五行·水】.\n对带有【五行·金】的敌人施加【易伤】效果，使目标受伤加重20%/30%/40%", attackType: "内功", rangeType: "范围", utilityType: "增益" },
    "金巫锋罡": { quality: "紫", img: "image/金巫锋罡.png", jineng: "【坐古剑殇】:召唤巨剑下劈对敌人造成大量伤害，并附加【五行·金】。\n对带有【五行·土】的敌人附加【摧金】效果，使目标外功受伤加重40%/50%/60%", attackType: "外功", rangeType: "范围", utilityType: "增益" },
    "李白": { quality: "紫", img: "image/李白.png", jineng: "【白虹剑意】:幻化巨剑下落造成大量伤害。\n【羁绊】【一梦黄粱】:幻化大量气剑持续落下，造成大量伤害", attackType: "内功", rangeType: "范围", utilityType: "" },
    "江无射": { quality: "紫", img: "image/江无射.png", jineng: "【贯穿矢】:长时间蓄力后，射出贯穿萌矢，对直线上的敌人造成巨额伤害。\n【羁绊】【一梦黄梁】:射出熔火巨前，落地后会爆炸造成大范围伤害。", attackType: "外功", rangeType: "范围", utilityType: "核心" },

    // --- 金卡 ---
    "薛魔主": { quality: "金", img: "image/薛魔主.png", jineng: "【盘蛇柱】:召唤蛇柱持续攻击造成大量伤害，对护盾三倍伤", attackType: "内功", rangeType: "范围", utilityType: "破盾" },
    "萨迦石神": { quality: "金", img: "image/萨迦石神.png", jineng: "【梵天之怒】:连续砸击地面对敌人造成巨额伤害，对护盾三倍伤害", attackType: "外功", rangeType: "范围", utilityType: "破盾" },
    "刘独峰": { quality: "金", img: "image/刘独峰.png", jineng: "【剑阵】:对周围敌人造成大量伤害", attackType: "外功", rangeType: "范围", utilityType: "" },
    "顾惜朝": { quality: "金", img: "image/顾惜朝.png", jineng: "【错综剑法】:造成多段单体伤害，短时间内每次攻击都会使下一次攻击伤害更高", attackType: "外功", rangeType: "单体", utilityType: "" },
    "楚相玉": { quality: "金", img: "image/楚相玉.png", jineng: "【赤焰寒光波】:长时间蓄力后对大范围的敌人造成巨额伤害", attackType: "内功", rangeType: "范围", utilityType: "" },
    "血鸦尊使": { quality: "金", img: "image/血鸦尊使.png", jineng: "【鸦羽断】:召唤巨剑突刺，对直线上的敌人造成巨额伤害。", attackType: "外功", rangeType: "范围", utilityType: "" },
    "血蛇尊使": { quality: "金", img: "image/血蛇尊使.png", jineng: "【剧毒蛇焰】:持续向前方喷射剧毒，造成少量伤害与50%减速然后再喷吐蛇焰，造成巨额伤害", attackType: "内功", rangeType: "范围", utilityType: "控制" },
    "魔尊血鹤": { quality: "金", img: "image/魔尊血鹤.png", jineng: "【四季之力】:根据羁绊【四时流转】内棋子的种类，施放额外的四季攻击，5种棋子时达到最大。", attackType: "内功", rangeType: "范围", utilityType: "" },
    "阿冷": { quality: "金", img: "image/阿冷.png", jineng: "【幽蝶光束】:召唤幽蝶光束扫过目标，对路径上的所有敌人造成巨大伤害。", attackType: "内功", rangeType: "范围", utilityType: "" },
    "柳星闻": { quality: "金", img: "image/柳星闻.png", jineng: "【月下剑舞】:连续舞剑，对周围的敌人持续造成大量伤害。\n【羁绊】【一梦黄梁】:召唤星陨，对命中的敌人造成巨大伤害", attackType: "外功", rangeType: "范围", utilityType: "" }
};